# Generated by Django 6.0.3 on 2026-03-13 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_following_user_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 10, 53, 2, 537623, tzinfo=datetime.timezone.utc)),
        ),
    ]
