# Generated by Django 6.0.3 on 2026-03-13 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_follow_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 10, 59, 57, 152370, tzinfo=datetime.timezone.utc)),
        ),
    ]
