# Generated by Django 6.0.3 on 2026-03-13 07:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='posts/covers/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('reading_time', models.PositiveIntegerField(default=1)),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='posts_status_bd5975_idx'), models.Index(fields=['created_at'], name='posts_created_060265_idx'), models.Index(fields=['published_at'], name='posts_publish_96a4df_idx'), models.Index(fields=['author', 'status'], name='posts_author__d284fa_idx')],
                'constraints': [models.UniqueConstraint(fields=('author', 'slug'), name='unique_author_slug')],
            },
        ),
    ]
