# Generated by Django 6.0.3 on 2026-03-13 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag_posttag_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 7, 50, 59, 514474, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 7, 50, 59, 513703, tzinfo=datetime.timezone.utc)),
        ),
    ]
