# Generated by Django 6.0.3 on 2026-03-13 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posttag_created_at_alter_tag_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posttag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 8, 56, 51, 479013, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 8, 56, 51, 478173, tzinfo=datetime.timezone.utc)),
        ),
    ]
