# Generated by Django 6.0.3 on 2026-03-13 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_bookmark_created_at_alter_posttag_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 10, 53, 2, 539712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 10, 53, 2, 538950, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 10, 53, 2, 538331, tzinfo=datetime.timezone.utc)),
        ),
    ]
