# Generated by Django 6.0.3 on 2026-03-13 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_bookmark_created_at_alter_posttag_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 10, 59, 57, 154506, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 10, 59, 57, 153698, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 10, 59, 57, 153096, tzinfo=datetime.timezone.utc)),
        ),
    ]
