# Generated by Django 6.0.3 on 2026-03-13 11:11

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_bookmark_created_at_alter_posttag_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 11, 11, 0, 932530, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 11, 11, 0, 931826, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 11, 11, 0, 931156, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='posts.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_posts_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['post', 'viewed_at'], name='post_views_post_id_e7e035_idx'), models.Index(fields=['user'], name='post_views_user_id_78fe02_idx'), models.Index(fields=['ip_address'], name='post_views_ip_addr_2660db_idx'), models.Index(fields=['viewed_at'], name='post_views_viewed__7bf7ac_idx')],
            },
        ),
    ]
